# Gemfile
source 'https://rubygems.org'

gem 'sinatra'
gem 'thin'
gem 'shotgun'
gem 'sinatra-activerecord'
gem 'sqlite3'
gem 'rake'
gem 'pry'
gem 'json'
gem 'sinatra-flash'
gem 'foundation'
gem 'compass'
gem 'sinatra-assetpack'
